### ISSUE TITLE
image uploads over the API failing

### ISSUE THREAD

**Issue by mhl** [mysociety/popit#718]
I'm getting a 500 error trying to upload an image over the API. It's being uploaded with:

```
curl -f --verbose --request POST --header APIKey: redacted -F notes="Manually uploaded from the command line" -F image=@'/home/mark/Downloads/Rik Photo.png' -F mime_type=image/png 'http://yournextmp.popit.mysociety.org/api/v0.1/persons/4715/image'
```

And production.log shows this error:

```
Error: stream ended unexpectedly
    at Form.<anonymous> (/data/vhost/popit.mysociety.org/popit/node_modules/express/node_modules/connect/node_modules/multiparty/index.js:681:24)
    at Form.emit (events.js:117:20)
    at finishMaybe (/data/vhost/popit.mysociety.org/popit/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (/data/vhost/popit.mysociety.org/popit/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at Form.Writable.end (/data/vhost/popit.mysociety.org/popit/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at onend (_stream_readable.js:501:10)
    at process._tickCallback (node.js:419:13)
127.0.0.1 - - [Thu, 08 Jan 2015 18:22:59 GMT] "POST /api/v0.1/persons/4715/image HTTP/1.1" 500 81 "-" "curl/7.35.0"
```

**Comment by chrismytton** [comment]
Hmm, I had thought that the API wouldn't be affected by the changes in #713, but the request is actually going through the popit middleware stack first, before it reaches the API, which seems to be what's causing this error.
