### ISSUE TITLE
persistent ECONNRESET error when reindexing a PopIt instance from cron

### ISSUE THREAD

**Issue by mhl** [mysociety/popit#740]
I'm setting up the nightly mirroring of Pombola instances' data -> PopIt, but the replace-database script is consistently failing at the point where it reindexes the data in Elasticsearch

```
node --eval 'var reIndex = require('\''popit-api'\'').reIndex;

var databaseName = process.argv[1];
console.warn("Reindexing the database: " + databaseName);

reIndex(databaseName, function(err, total) {
  if (err) {
    throw err;
  }
  console.log("Re-indexed " + total + " docs from " + databaseName);
  process.exit();
});' popit_staging_south-africa_20150206102510
Reindexing the database: popit_staging_south-africa_20150206102510
Elasticsearch ERROR: 2015-02-06T10:36:02Z
  Error: Request error, retrying -- read ECONNRESET
      at Log.error (/data/vhost/popit.staging.mysociety.org/popit/node_modules/popit-api/node_modules/elasticsearch/src/lib/log.js:213:60)
      at checkRespForFailure (/data/vhost/popit.staging.mysociety.org/popit/node_modules/popit-api/node_modules/elasticsearch/src/lib/transport.js:185:18)
      at HttpConnector.<anonymous> (/data/vhost/popit.staging.mysociety.org/popit/node_modules/popit-api/node_modules/elasticsearch/src/lib/connectors/http.js:150:7)
      at ClientRequest.bound (/data/vhost/popit.staging.mysociety.org/popit/node_modules/popit-api/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:56:17)
      at ClientRequest.emit (events.js:95:17)
      at Socket.socketErrorListener (http.js:1547:9)
      at Socket.emit (events.js:95:17)
      at net.js:440:14
      at process._tickCallback (node.js:419:13)

Elasticsearch WARNING: 2015-02-06T10:36:02Z
  Unable to revive connection: http://localhost:9200/

Elasticsearch WARNING: 2015-02-06T10:36:02Z
  No living connections


[eval]:8
    throw err;
          ^
Error: No Living connections
    at sendReqWithConnection (/data/vhost/popit.staging.mysociety.org/popit/node_modules/popit-api/node_modules/elasticsearch/src/lib/transport.js:170:15)
    at next (/data/vhost/popit.staging.mysociety.org/popit/node_modules/popit-api/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
    at process._tickCallback (node.js:419:13)
```

**Comment by Flupsy** [comment]
For the record: I've given elasticsearch some more memory (up to 1GB from 512MB) on pluto.

**Comment by chrismytton** [comment]
Memory boost seems to have fixed this so closing this ticket. Please re-open if you see this again.

**Comment by mhl** [comment]
I get this locally when trying reindex a PopIt instance, even after having raised ES_HEAP_SIZE to 1GB, then 2GB and restarting Elasticsearch:

```
+ read -r -d '' REINDEX_SCRIPT
+ true
+ node --eval 'var reIndex = require('\''popit-api'\'').reIndex;

var databaseName = process.argv[1];
console.warn("Reindexing the database: " + databaseName);

reIndex(databaseName, function(err, total) {
  if (err) {
    throw err;
  }
  console.log("Re-indexed " + total + " docs from " + databaseName);
  process.exit();
});' popitdev_candidates_20150413073538
Failed to load c++ bson extension, using pure JS version
Reindexing the database: popitdev_candidates_20150413073538
Elasticsearch ERROR: 2015-04-13T06:38:06Z
  Error: Request error, retrying -- read ECONNRESET
      at Log.error (/home/mark/popit/popit-api/node_modules/elasticsearch/src/lib/log.js:213:60)
      at checkRespForFailure (/home/mark/popit/popit-api/node_modules/elasticsearch/src/lib/transport.js:185:18)
      at HttpConnector.<anonymous> (/home/mark/popit/popit-api/node_modules/elasticsearch/src/lib/connectors/http.js:141:7)
      at ClientRequest.bound (/home/mark/popit/popit-api/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:52:17)
      at ClientRequest.EventEmitter.emit (events.js:95:17)
      at Socket.socketErrorListener (http.js:1547:9)
      at Socket.EventEmitter.emit (events.js:95:17)
      at net.js:441:14
      at process._tickCallback (node.js:415:13)

Elasticsearch ERROR: 2015-04-13T06:38:13Z
  Error: Request error, retrying -- read ECONNRESET
      at Log.error (/home/mark/popit/popit-api/node_modules/elasticsearch/src/lib/log.js:213:60)
      at checkRespForFailure (/home/mark/popit/popit-api/node_modules/elasticsearch/src/lib/transport.js:185:18)
      at HttpConnector.<anonymous> (/home/mark/popit/popit-api/node_modules/elasticsearch/src/lib/connectors/http.js:141:7)
      at ClientRequest.bound (/home/mark/popit/popit-api/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:52:17)
      at ClientRequest.EventEmitter.emit (events.js:95:17)
      at Socket.socketErrorListener (http.js:1547:9)
      at Socket.EventEmitter.emit (events.js:95:17)
      at net.js:441:14
      at process._tickCallback (node.js:415:13)

Elasticsearch ERROR: 2015-04-13T06:38:16Z
  Error: Request error, retrying -- read ECONNRESET
      at Log.error (/home/mark/popit/popit-api/node_modules/elasticsearch/src/lib/log.js:213:60)
      at checkRespForFailure (/home/mark/popit/popit-api/node_modules/elasticsearch/src/lib/transport.js:185:18)
      at HttpConnector.<anonymous> (/home/mark/popit/popit-api/node_modules/elasticsearch/src/lib/connectors/http.js:141:7)
      at ClientRequest.bound (/home/mark/popit/popit-api/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:52:17)
      at ClientRequest.EventEmitter.emit (events.js:95:17)
      at Socket.socketErrorListener (http.js:1547:9)
      at Socket.EventEmitter.emit (events.js:95:17)
      at net.js:441:14
      at process._tickCallback (node.js:415:13)

Elasticsearch ERROR: 2015-04-13T06:38:22Z
  Error: Request complete with error -- read ECONNRESET
      at Log.error (/home/mark/popit/popit-api/node_modules/elasticsearch/src/lib/log.js:213:60)
      at checkRespForFailure (/home/mark/popit/popit-api/node_modules/elasticsearch/src/lib/transport.js:188:18)
      at HttpConnector.<anonymous> (/home/mark/popit/popit-api/node_modules/elasticsearch/src/lib/connectors/http.js:141:7)
      at ClientRequest.bound (/home/mark/popit/popit-api/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:52:17)
      at ClientRequest.EventEmitter.emit (events.js:95:17)
      at Socket.socketErrorListener (http.js:1547:9)
      at Socket.EventEmitter.emit (events.js:95:17)
      at net.js:441:14
      at process._tickCallback (node.js:415:13)


[eval]:8
    throw err;
          ^
Error: Error: read ECONNRESET
    at checkRespForFailure (/home/mark/popit/popit-api/node_modules/elasticsearch/src/lib/transport.js:189:17)
    at HttpConnector.<anonymous> (/home/mark/popit/popit-api/node_modules/elasticsearch/src/lib/connectors/http.js:141:7)
    at ClientRequest.bound (/home/mark/popit/popit-api/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:52:17)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
```

**Comment by Flupsy** [comment]
Is there anything useful in your local elasticsearch log when this happens?

**Comment by mhl** [comment]
Several "TooLongFrameException: HTTP content length exceeded 104857600 bytes" exceptions (see below) - the suggestions [here](https://github.com/elastic/elasticsearch/issues/2137) seem to be:

* Using the wrong port (9200 vs 9300)
* Changing `http.max_content_length`

```
[2015-04-13 09:36:29,105][INFO ][cluster.metadata         ] [Llyron] [popitdev_candidates_20150413093607] creating index, cause [auto(bulk api)], shards [5]/[1], mappings []
[2015-04-13 09:36:31,385][INFO ][cluster.metadata         ] [Llyron] [popitdev_candidates_20150413093607] update_mapping [person] (dynamic)
[2015-04-13 09:36:34,432][INFO ][cluster.metadata         ] [Llyron] [popitdev_candidates_20150413093607] update_mapping [organization] (dynamic)
[2015-04-13 09:38:03,011][INFO ][monitor.jvm              ] [Llyron] [gc][young][41440][312] duration [1.5s], collections [2]/[1.8s], total [1.5s]/[26.5s], memory [2.4gb]->[2.6gb]/[3.9gb], all_pools {[young] [2.1mb]->[612.2kb]/[266.2mb]}{[survivor] [12mb]->[4.9mb]/[33.2mb]}{[old] [2.4gb]->[2.6gb]/[3.6gb]}
[2015-04-13 09:38:04,643][WARN ][monitor.jvm              ] [Llyron] [gc][young][41441][313] duration [1.5s], collections [1]/[1.6s], total [1.5s]/[28s], memory [2.6gb]->[2.7gb]/[3.9gb], all_pools {[young] [612.2kb]->[87.9mb]/[266.2mb]}{[survivor] [4.9mb]->[10mb]/[33.2mb]}{[old] [2.6gb]->[2.6gb]/[3.6gb]}
[2015-04-13 09:38:06,244][WARN ][monitor.jvm              ] [Llyron] [gc][young][41442][314] duration [1.4s], collections [1]/[1.6s], total [1.4s]/[29.5s], memory [2.7gb]->[2.7gb]/[3.9gb], all_pools {[young] [87.9mb]->[2.4mb]/[266.2mb]}{[survivor] [10mb]->[6.9mb]/[33.2mb]}{[old] [2.6gb]->[2.7gb]/[3.6gb]}
[2015-04-13 09:38:06,310][WARN ][http.netty               ] [Llyron] Caught exception while handling client http traffic, closing connection [id: 0x3e86acf4, /127.0.0.1:52970 => /127.0.0.1:9200]
org.elasticsearch.common.netty.handler.codec.frame.TooLongFrameException: HTTP content length exceeded 104857600 bytes.
        at org.elasticsearch.common.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:169)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:701)
[2015-04-13 09:38:09,888][INFO ][monitor.jvm              ] [Llyron] [gc][young][41445][317] duration [1.4s], collections [2]/[1.6s], total [1.4s]/[31s], memory [3gb]->[2.8gb]/[3.9gb], all_pools {[young] [256.4mb]->[3.8mb]/[266.2mb]}{[survivor] [29.7mb]->[8.3mb]/[33.2mb]}{[old] [2.7gb]->[2.8gb]/[3.6gb]}
[2015-04-13 09:38:11,656][WARN ][monitor.jvm              ] [Llyron] [gc][young][41446][318] duration [1.5s], collections [1]/[1.7s], total [1.5s]/[32.6s], memory [2.8gb]->[2.9gb]/[3.9gb], all_pools {[young] [3.8mb]->[3.1mb]/[266.2mb]}{[survivor] [8.3mb]->[7.3mb]/[33.2mb]}{[old] [2.8gb]->[2.9gb]/[3.6gb]}
[2015-04-13 09:38:13,074][WARN ][monitor.jvm              ] [Llyron] [gc][young][41447][319] duration [1.1s], collections [1]/[1.4s], total [1.1s]/[33.8s], memory [2.9gb]->[3.1gb]/[3.9gb], all_pools {[young] [3.1mb]->[88.4mb]/[266.2mb]}{[survivor] [7.3mb]->[10.7mb]/[33.2mb]}{[old] [2.9gb]->[3gb]/[3.6gb]}
[2015-04-13 09:38:14,817][WARN ][monitor.jvm              ] [Llyron] [gc][young][41448][320] duration [1.6s], collections [1]/[1.7s], total [1.6s]/[35.4s], memory [3.1gb]->[3.1gb]/[3.9gb], all_pools {[young] [88.4mb]->[2.6mb]/[266.2mb]}{[survivor] [10.7mb]->[7mb]/[33.2mb]}{[old] [3gb]->[3.1gb]/[3.6gb]}
[2015-04-13 09:38:14,851][WARN ][http.netty               ] [Llyron] Caught exception while handling client http traffic, closing connection [id: 0x524f7fb9, /127.0.0.1:52972 => /127.0.0.1:9200]
org.elasticsearch.common.netty.handler.codec.frame.TooLongFrameException: HTTP content length exceeded 104857600 bytes.
        at org.elasticsearch.common.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:169)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:701)
[2015-04-13 09:38:21,893][INFO ][monitor.jvm              ] [Llyron] [gc][young][41454][324] duration [1.6s], collections [2]/[1.8s], total [1.6s]/[37.8s], memory [3.1gb]->[3.2gb]/[3.9gb], all_pools {[young] [3mb]->[3.4mb]/[266.2mb]}{[survivor] [12.6mb]->[4.5mb]/[33.2mb]}{[old] [3.1gb]->[3.1gb]/[3.6gb]}
[2015-04-13 09:38:23,519][WARN ][monitor.jvm              ] [Llyron] [gc][young][41455][325] duration [1.5s], collections [1]/[1.6s], total [1.5s]/[39.3s], memory [3.2gb]->[3.3gb]/[3.9gb], all_pools {[young] [3.4mb]->[88.3mb]/[266.2mb]}{[survivor] [4.5mb]->[9.9mb]/[33.2mb]}{[old] [3.1gb]->[3.2gb]/[3.6gb]}
[2015-04-13 09:38:25,048][WARN ][monitor.jvm              ] [Llyron] [gc][young][41456][326] duration [1.3s], collections [1]/[1.5s], total [1.3s]/[40.6s], memory [3.3gb]->[3.3gb]/[3.9gb], all_pools {[young] [88.3mb]->[4.9mb]/[266.2mb]}{[survivor] [9.9mb]->[6.9mb]/[33.2mb]}{[old] [3.2gb]->[3.3gb]/[3.6gb]}
[2015-04-13 09:38:25,057][WARN ][http.netty               ] [Llyron] Caught exception while handling client http traffic, closing connection [id: 0x7559e7d0, /127.0.0.1:52974 => /127.0.0.1:9200]
org.elasticsearch.common.netty.handler.codec.frame.TooLongFrameException: HTTP content length exceeded 104857600 bytes.
        at org.elasticsearch.common.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:169)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:701)
[2015-04-13 09:38:29,750][INFO ][monitor.jvm              ] [Llyron] [gc][young][41460][331] duration [1.4s], collections [2]/[1.6s], total [1.4s]/[43s], memory [2.8gb]->[2.8gb]/[3.9gb], all_pools {[young] [160.1mb]->[88.7mb]/[266.2mb]}{[survivor] [6.9mb]->[10.3mb]/[33.2mb]}{[old] [2.6gb]->[2.7gb]/[3.6gb]}
[2015-04-13 09:38:31,444][WARN ][monitor.jvm              ] [Llyron] [gc][young][41461][332] duration [1.5s], collections [1]/[1.7s], total [1.5s]/[44.6s], memory [2.8gb]->[2.8gb]/[3.9gb], all_pools {[young] [88.7mb]->[3.3mb]/[266.2mb]}{[survivor] [10.3mb]->[7mb]/[33.2mb]}{[old] [2.7gb]->[2.8gb]/[3.6gb]}
[2015-04-13 09:38:31,508][WARN ][http.netty               ] [Llyron] Caught exception while handling client http traffic, closing connection [id: 0xad6232d1, /127.0.0.1:52976 => /127.0.0.1:9200]
org.elasticsearch.common.netty.handler.codec.frame.TooLongFrameException: HTTP content length exceeded 104857600 bytes.
        at org.elasticsearch.common.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:169)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:701)
```

**Comment by lizconlan** [comment]
I eventually coaxed it to complete on my vagrant box by setting 
`http.max_content_length: 512mb` in /etc/elasticsearch/elasticsearch.yml

I'd already set ES_HEAP_SIZE to 1GB by that point, which wasn't enough to avoid a crash on its own, so it would be interesting to see whether this is necessary but I'm not up for running it again this evening to find out.

It looks as though the suggestion about port 9200 vs 9300 is a red herring for our use case though.

**Comment by Flupsy** [comment]
Let me know whether you want me to make that change on pluto.

**Comment by mhl** [comment]
This fixed it for me locally too; I'd say it's worth making that change on pluto too, unless there's an obvious drawback I haven't spotted.

**Comment by Flupsy** [comment]
I've made this change on pluto and restarted elasticsearch.
