### ISSUE TITLE
image uploads are failing

### ISSUE THREAD

**Issue by mhl** [mysociety/popit#751]
The upload returns a 503 and the node process restarts - this error is in the logs:

```
/data/vhost/popit.mysociety.org/popit/node_modules/popit-api/src/routes/image.js:206
        res.saveImages( doc, image, upload, dest_path );
            ^
TypeError: Object #<ServerResponse> has no method 'saveImages'
    at /data/vhost/popit.mysociety.org/popit/node_modules/popit-api/src/routes/image.js:206
:13
    at /data/vhost/popit.mysociety.org/popit/node_modules/mkdirp/index.js:20:20
    at Object.oncomplete (fs.js:107:15)
```

**Comment by chrismytton** [comment]
@mhl I've deployed a fix for this to the production site.
