### ISSUE TITLE
Deletion of Members of large orgnizations triggers traceback with Popit UI

### ISSUE THREAD

**Issue by kaerumy** [mysociety/popit#828]
https://sinar-malaysia.popit.mysociety.org/organizations/536844f619ee29270d8a9f63

````
Express
413 Error: request entity too large
   at makeError (/data/vhost/popit.mysociety.org/popit-2015-04-20T17-04-55/node_modules/body-parser/node_modules/raw-body/index.js:184:15)
   at module.exports (/data/vhost/popit.mysociety.org/popit-2015-04-20T17-04-55/node_modules/body-parser/node_modules/raw-body/index.js:40:15)
   at read (/data/vhost/popit.mysociety.org/popit-2015-04-20T17-04-55/node_modules/body-parser/lib/read.js:62:3)
   at Object.urlencodedParser [as handle] (/data/vhost/popit.mysociety.org/popit-2015-04-20T17-04-55/node_modules/body-parser/lib/types/urlencoded.js:84:5)
   at next (/data/vhost/popit.mysociety.org/popit-2015-04-20T17-04-55/node_modules/express/node_modules/connect/lib/proto.js:174:15)
   at Object.jsonParser [as handle] (/data/vhost/popit.mysociety.org/popit-2015-04-20T17-04-55/node_modules/body-parser/lib/types/json.js:83:36)
   at next (/data/vhost/popit.mysociety.org/popit-2015-04-20T17-04-55/node_modules/express/node_modules/connect/lib/proto.js:174:15)
   at Object.expressInit [as handle] (/data/vhost/popit.mysociety.org/popit-2015-04-20T17-04-55/node_modules/express/lib/middleware.js:30:5)
   at next (/data/vhost/popit.mysociety.org/popit-2015-04-20T17-04-55/node_modules/express/node_modules/connect/lib/proto.js:174:15)
   at Object.query [as handle] (/data/vhost/popit.mysociety.org/popit-2015-04-20T17-04-55/node_modules/express/node_modules/connect/lib/middleware/query.js:43:5)
````

**Comment by kaerumy** [comment]
Note feel free to test deleting any member or members from this orgnanization, "Parliament of Malaysia" it is no longer used and a copy already exists as "House of Representatives"

**Comment by kaerumy** [comment]
Seems to happen for any organization with large set of members.
